### ISSUE TITLE
Conflict with Archipelago OOT client 0.3.1

### ISSUE THREAD

**Issue by coavins** [coavins/EmoTrackerPacks#2]
There appears to be a conflict between the CrowdControl connector lua for Bizhawk 2.3 and the OOT lua for AP OOT client 0.3.1. Running both in Bizhawk at the same time causes problems for the AP script.

**Comment by coavins** [comment]
This issue has been resolved with a new version of the CrowdControl connector lua, available here: https://github.com/coavins/bizhawk-connector

The AP OOT lua will run together with this new bizhawk connector if you load the AP lua first.

**Comment by DJChupa13** [comment]
@coavins Archipelago 0.3.2 launched today, and it appears that your steps from before (load AP lua before loading Emotracker's connector lua) does not work. Connecting the Emotracker lua breaks the connection as described in the Archipelago client:

"Lost connection to N64 and attempting to reconnect.  Use /n64 for status updates."

Using the /n64 command yields "N64 Status: Initial Connection Made" but no connection is made, and no items are sent/received.  Only when Bizhawk is closed and the AP lua is loaded do items start to once again flow.

I'm not exactly sure if the 0.3.2 update is to blame - it just so happens that I started using your tracker pack today.  If it helps, I'm on BizHawk 2.4.2, which appears to be the latest version (or one of the latest - didn't test much) that supports the Emotracker lua connector - your About page mentions compatibility up to 2.8, however I tried both 2.7 and 2.8 and could not load the Emotracker lua.  In doing so, I get a message in Bizhawk:

"Crowd Control requires BizHawk 2.3 or 2.3.1 to function"

So...I guess you can consider this note a double issue XD hope you can help!

**Comment by coavins** [comment]
@DJChupa13 Thanks for the report. This issue was fixed with a new version of the connector lua for bizhawk. Please give it a try and let me know if you're still having trouble:

https://github.com/coavins/bizhawk-connector/releases

**Comment by coavins** [comment]
I updated the readme to make it more clear that you have to use this version of the connector lua.

**Comment by DJChupa13** [comment]
My hero, thank you!
